### ISSUE TITLE
rtsp_player_audio.js:41 [mse] Error occured: PIPELINE_ERROR_DECODE: Failed to send audio packet for decoding

### ISSUE THREAD

**Issue by salim-hbk** [Streamedian/html5_rtsp_player#102]
Hi, Streamedian 
Thanks for making this project open source.
 I'm getting below error on Chrome browser on version above 63.

> rtsp_player_audio.js:41 [mse] Error occured: PIPELINE_ERROR_DECODE: Failed to send audio packet for decoding: timestamp=103936000 duration=64000 size=144 side_data_size=0 is_key_frame=1 encrypted=0 discard_padding (us)=(0, 0)

If I doesn't handle the Audio, then MSE doesn't throw the exception.
Quite interestingly this kind of bug also being raised by some other people on HLS player (https://github.com/video-dev/hls.js/pull/1867)

I've customised the code to fit my use-case as I'm getting multiple rtp data in every packet accordingly changed the code to fit.

It quite frequently also prints below lines to console
[remuxer:h264] invalid AVC sample duration at PTS/DTS: 3142926/3142926|lastDTS: 3145380:-2454.

Could you please suggest me how to handle this situation. below I've attached the file containing the video data.

[dataNew (2).txt](https://github.com/Streamedian/html5_rtsp_player/files/2546887/dataNew.2.txt)

**Comment by salim-hbk** [comment]
Hi 
is there any update on above question

**Comment by victorgrenke** [comment]
try to use the version 1.8.2  https://streamedian.com/cabinet/downloads/player/

**Comment by salim-hbk** [comment]
Thank you, I will test and get back to you in a day

**Comment by salim-hbk** [comment]
Hi: Victor G
I've tested the build version 1.8.2. I'm getting the same behaviour from the player but this time it is not throwing [mse] Error occured: PIPELINE_ERROR_DECODE. It all together halts video play back(A kind of Crash behaviour). If you could possibly guide me what is going wrong I can try to fix it. I can provide additional behaviour if you want.

**Comment by victorgrenke** [comment]
what's audio format in your stream?

**Comment by salim-hbk** [comment]
Hi: Victor 
Audio format you have requested is AAC.
below is the DESCRIBE response of audio part. Let me know if you need some more info.

m=audio 0 RTP/AVP 98
a=rtpmap:98 mpeg4-generic/16000/1
a=fmtp:98 streamtype=5; profile-level-id=15; mode=AAC-hbr; config=1408; SizeLength=13;IndexLength=3; IndexDeltaLength=3; Profile=1;

**Comment by victorgrenke** [comment]
`a=rtpmap:98 mpeg4-generic/16000/1` - it's MPEG-4 Elementary Streams, should be H264/90000

**Comment by salim-hbk** [comment]
Is it possible change anything at client side to support sampling of 16K audio. As I have read online for human speech sampling rate of 16K is sufficient.

**Comment by salim-hbk** [comment]
Hi, 
I have resolved this issue, Player is working all good, you can close this ticket. Thank you again for this open source project.
