### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by MathieuDuponchelle** [Streamedian/html5_rtsp_player#105]
Since the last commit, when serving the example from the example subdirectory after a `git clone`, playback never starts. I see that RTSP messages are correctly exchanged,, and "got data" is logged in the console, but the stream is never displayed.

I notice that `index.html` was updated in the latest commit, but the minified javascript was not. When trying to build it:

```
npm install
./node_modules/rollup/bin/rollup -c
```

I get the following error:

```
Error parsing /home/meh/devel/sandbox/html5_rtsp_player_master/src/player.js: Unexpected token (169:10) in /home/meh/devel/sandbox/html5_rtsp_player_master/src/player.js
```

The example works all right in the previous commit (https://github.com/Streamedian/html5_rtsp_player/commit/68ac0a3d7df23a98da8de4b307c12bb62d27b97a), and I can also build the minified javascript all right.

Let me know if you need more info!

**Comment by MathieuDuponchelle** [comment]
ping ?

**Comment by olanMbakop** [comment]
I got the same error. Running `rollup -c` shows parsing error 
`Error parsing /home/meh/devel/sandbox/html5_rtsp_player_master/src/player.js: Unexpected token (169:10) in /home/meh/devel/sandbox/html5_rtsp_player_master/src/player.js`
