### ISSUE TITLE
user:pass authentication

### ISSUE THREAD

**Issue by ferglezt** [Streamedian/html5_rtsp_player#11]
Hello. 

I'm trying to use this project in order to get RTSP stream from a Dahua IP Camera. The URL to get the stream is something like: 

rtsp://192.168.xx.xx:554/cam/realmonitor?channel=CHANNEL&subtype=ENCODING&authbasic=BASE_64_USER:PASS

So far so good, I haven't been able to get the stream, even though it works with VLC media player and VXG Chrome plugin.

Is it possible to get the stream from the  RTSP proxy with a URL like that? I've already tested the project with rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov and everything flows smooth and nice.

**Comment by victorgrenke** [comment]
thanks we will try to check it.

**Comment by victorgrenke** [comment]
rtsp://192.168.xx.xx:554/cam/realmonitor?channel=CHANNEL&subtype=ENCODING&authbasic=BASE_64_USER:PASS

this is your local path - it should be global to proxy can work with it.

**Comment by ferglezt** [comment]
@victorgrenke Sorry for being so noob, but how can I make the path global to proxy? Thanks for the support.

**Comment by victorgrenke** [comment]
make port forwarding in your router and IP address will be not interanl 192.168.xx.xx:554 (of course if you have global IP address from your provider)

**Comment by kreopt** [comment]
Digest and Basic auth supported in latest version
