### ISSUE TITLE
RTP media pkg  definition logic error

### ISSUE THREAD

**Issue by fast0490f** [Streamedian/html5_rtsp_player#112]
Hi, I decided to update the version of my player and found out that no camera is working. Having looked at the code I found contradictions of logic [here](https://github.com/Streamedian/html5_rtsp_player/blob/master/src/client/rtsp/client.js#L563), after deleting this line, everything works

**Comment by fast0490f** [comment]
This fix has been made @victorgrenke please see if you have time

**Comment by victorgrenke** [comment]
please make pull request

**Comment by fast0490f** [comment]
@victorgrenke #113
