### ISSUE TITLE
RTSP Not Working

### ISSUE THREAD

**Issue by slimshadddyyy** [Streamedian/html5_rtsp_player#12]
Hi Victor,

Thanks for the great plugin. However, I am facing some issues while integration. I am using VLC web plugin to play RTSP URL's but your plugin sounds legit to us considering VLC performance issue and lack of browser support except IE and FF.

I am stuck in below issues
1. How to setup player in JS ?
2. Where do I place webpack.config.js and how to configure it ?
3. How do I run RTSP URL fetched from our streaming server ? is it possible to directly run sample RTSP like  this rtsp://media.smart-streaming.com/mytest/mp4:sample.mp4 ?

If I attach big bunny rtsp it throws exception `Failed to parse SDP`. I am using `test.bundle.js` same as in your example.

Can this work with multiple video players with one single playback controls ?

Also the example https://specforge.com/html5playerstream/index.html does not work in chrome while browser support is mentioned.

Please guide and help.

Thanks !

**Comment by victorgrenke** [comment]
the palyer and proxy design were changed significantly, many problems are gone, some latter I will update

**Comment by mburger81** [comment]
Hi, @slimshadddyyy was you able to implement it and got it work?
We are not able to get it work.
We can not create the test.bundle.js from git and also downloaded the test.bundle.js from specforge example index.htm page!

Also we try to implement the websocket by our own, but we are not sure how to do this.

Some info or code to share with us?

**Comment by kreopt** [comment]
@mburger81 , you can find protocol description for websocket transport in updated readme. Note that it works only for latest player version
