### ISSUE TITLE
当RTP时间戳达到最大值恢复到最小值的时候，播放器不会加载RTP，会一直丢弃

### ISSUE THREAD

**Issue by PeZQ** [Streamedian/html5_rtsp_player#124]
您好，这是一个非常棒的项目，感谢您的分享。
         在此过程中，我测试到摄像头的rtp包时间戳达到最大值的时候，下一包会恢复到比较小的值，这时候码流依然存在，但是播放器不加载了。通常情况下的最大值是2的32次方乘与90000.期待您的回复。谢谢

**Comment by PeZQ** [comment]
一个是可播放器的清理，一个是当前播放时间的跳转。在MSEBuffer的updateend里面修改。

**Comment by chongyangwang** [comment]
@PeZQ    您好   方便请教一下么
我的问题是在运行作者示例demo的时候   去生成  streamedian.js   出错

![image](https://user-images.githubusercontent.com/32251099/60635070-e8f6da00-9e43-11e9-861d-e09d320c13da.png)

请问这是什么原因呢    看您最近的issues是10天前    所以不好意思 来打扰您一下
