### ISSUE TITLE
Cant play with rtsp type h265?

### ISSUE THREAD

**Issue by phuhv56** [Streamedian/html5_rtsp_player#127]
Hi everyone,
I got a problem with RTSP stream. This is link i can play [rtsp://<user>:<pass>@<host>:5541/Streaming/Channels/202/](url)
v=0
o=StreamingServer 3433055887 1562048224529361 IN IP4 192.168.1.228
s=av0_1
e=NONE
c=IN IP4 0.0.0.0
t=0 0
m=video 0 RTP/AVP 96
b=AS:70
a=control:trackID=1
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=4d001e;packetization-mode=1;sprop-parameter-sets=Z00AHp2oKA9puAgICBA=,aO48gA==
a=Media_header:MEDIAINFO=494D4B48010100000400010000000000000000000000000000000000000000000000000000000000;

And this link i can not play: 
[rtsp://<user>:<pass>@<host>:5541/Streaming/Channels/201/](url)
v=0
o=- 1109162014219182 0 IN IP4 0.0.0.0
s=HIK Media Server V3.4.101
i=HIK Media Server Session Description : standard
e=NONE
c=IN IP4 0.0.0.0
t=0 0
a=control:*
b=AS:2058
a=range:npt=now-
m=video 0 RTP/AVP 96
i=Video Media
a=rtpmap:96 H265/90000
a=control:trackID=video
b=AS:2048
a=Media_header:MEDIAINFO=494D4B48020100000400050000000000000000000000000000000000000000000000000000000000;
a=appversion:1.0

**Is Player supported H265? Or any proplem with both of link? Please help me! Many Thanks**

**Comment by victorgrenke** [comment]
the oneself html5 player doesn't support H265.
please review 
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility

**Comment by phuhv56** [comment]
Thanks alot I got it.
