### ISSUE TITLE
How to improve the video latency 

### ISSUE THREAD

**Issue by zackxue** [Streamedian/html5_rtsp_player#14]
Current the video latency is about 2s, how to improve the latency?

**Comment by victorgrenke** [comment]
do you use own installed proxy on your side?

**Comment by zackxue** [comment]
no proxy, just a http server

**Comment by zackxue** [comment]
how about your test result for the latency?

**Comment by victorgrenke** [comment]
close to 1 sec, I have new version different fron github

**Comment by zackxue** [comment]
Good news, can we try that version, it is server or the client for reduce the latency?

**Comment by kreopt** [comment]
New version is out some time ago. You can try it at http://streamedian.com
