### ISSUE TITLE
Websocket proxy on other platforms (i.e. MacoSX?)

### ISSUE THREAD

**Issue by HughAndersonNUS** [Streamedian/html5_rtsp_player#15]
Hi,
I wondered if it was possible to have this websocket/rtsp proxy running on other platforms - I cannot seem to find the source for it, and would like to run it on my Mac...
Cheers Hugh

**Comment by mburger81** [comment]
Hi @HughAndersonNUS did you got it work?
We are trying to implement it also but we are not able to do it.

**Comment by victorgrenke** [comment]
This is installer for MAC https://www.dropbox.com/s/5n09lkg2v7dvn0h/Streamedian%20WS%20RTSP%20Proxy%20Server%201.8.dmg?dl=0
