### ISSUE TITLE
Site is down 

### ISSUE THREAD

**Issue by abhik261738** [Streamedian/html5_rtsp_player#155]
![Screenshot from 2020-02-06 11-26-05](https://user-images.githubusercontent.com/52736098/73909785-87b05100-48d3-11ea-9443-224dfa1b7418.png)

**Comment by cahitbeyaz** [comment]
follow: #153

**Comment by victorgrenke** [comment]
oh yes, the domain registrar's DNS servers were hacked (godaddy) and on our domain names we changed addresses to servers with viruses. Great and powerful Google sent the streamedian.com domain name immediately to the red list. Now we wait when they check the site and remove this red warning. Google's reverse process is not fast ^^. In fact, the website was not broken and is in working condition now, you can try to log in from other browsers. Sorry for that!

**Comment by abhik261738** [comment]
k i have some issue during the streaming..can you please help me to find the solution
![Screenshot from 2020-02-06 13-21-16](https://user-images.githubusercontent.com/52736098/73923858-8b52d080-48f1-11ea-8357-cc49f24251a3.png)
