### ISSUE TITLE
Solution can work with IP camera 

### ISSUE THREAD

**Issue by bhavin44** [Streamedian/html5_rtsp_player#16]
Hi,

I am having IP camera and want to play RTSP h.264 stream on chrome browser. Is it working with this solution ?

**Comment by jerry-he** [comment]
i have the same question  , do u have resolve it? my email   soft@shangcha.cc

**Comment by videoanalytica** [comment]
It should work, as long as its a standard rtsp stream.

**Comment by videoanalytica** [comment]
It should work, as long as its a standard rtsp stream.
