### ISSUE TITLE
WSS connection to rtsp proxy?

### ISSUE THREAD

**Issue by InstanT977** [Streamedian/html5_rtsp_player#18]
Hello, my site working on https protocol, and so i need wss connection to rtsp proxy...but i cant find property in rtsp proxy config to configurate WSS connection.. anyone can help me? How i can do it?

Thank you in advance for your response!

**Comment by kreopt** [comment]
WSS is currently not supported in standalone proxy. You can use Nginx as a toplevel proxy to achieve this
