### ISSUE TITLE
ARM Test

### ISSUE THREAD

**Issue by lorlor** [Streamedian/html5_rtsp_player#180]
Hi @victorgrenke ,

Thanks for your work on this art repo. And now I want to test this repo on ARM v8 platform. However, it seems like that ws-rtsp-proxy does not support ARM v8. My question is: could I get support for testing this repo on ARM v8 ?

Any help will be appreciated.

Thank you.

**Comment by victorgrenke** [comment]
Hello @lorlor  the proxy didn't compiled for the ARM v8 platform. but it's possible to do. what board do you use? or do you use your own design?

**Comment by wartek69** [comment]
Hi @victorgrenke 
I'd like to deploy the proxy on a Jetson Xavier (aarch64/ubuntu18.04).
Is it possible to have a build for this platform?
BR
Alex

**Comment by WanHui666** [comment]
> Hi @victorgrenke I'd like to deploy the proxy on a Jetson Xavier (aarch64/ubuntu18.04). Is it possible to have a build for this platform? BR Alex

Hi, Alex. Do you have got the ARM deb package? I have the same request, and send e-mails also. But not response currently @StreamSupp

**Comment by wartek69** [comment]
Hi @WanHui666 
Unfortunately no response so far...
If you'd get a response on your mail please keep us updated!

**Comment by WanHui666** [comment]
> Hi @WanHui666 Unfortunately no response so far... If you'd get a response on your mail please keep us updated!

Ah.. Thanks for your response. If I got the response, I will sync to you.
I need to find the other way to show video on web page, do you have other ideas?

**Comment by WanHui666** [comment]
> Hello @lorlor the proxy didn't compiled for the ARM v8 platform. but it's possible to do. what board do you use? or do you use your own design?

Hi, VictorG

Do you have the plan to support ARM platform for proxy server?Maybe it's hard to find an ARM platform device.
Is it OK to build in virtual machine? Such as Azure or AWS? You can use it for trial and choose the ARM arch machine, then push code and build DEB package...

Looking forward to hearing from you.

**Comment by victorgrenke** [comment]
Hi @WanHui666 
Previous versions of proxy were built for ARM (raspberry pi + ubuntu), but they were of little demand and DEB packets were removed from the website. You are right to find a ARM hardware is specific task :) Thanks for the advice on how to get around this with virtual machines. I will try to do this and get back to you.
