### ISSUE TITLE
Why there is need of licence 

### ISSUE THREAD

**Issue by dhaval2017** [Streamedian/html5_rtsp_player#188]
Hi if source code is available
Why it asks for licence?
Can I setup everything on my server and use it as always free?

**Comment by victorgrenke** [comment]
Player is free you can use it as you wish. All sources are available here. For this player technology need to use proxy server. Proxy can be written by anyone, commands can be found in docs and player source. Many people had already done it. If someone don't want or not have time to write their own proxy they can use our version of proxy. There are free license or not free it depends on number of rtsp sources and goals. So license's not for player it's for our version of proxy.  "Can I setup everything on my server and use it as always free?" it's possible

**Comment by dhaval2017** [comment]
Hi @victorgrenke thanks for quick response
I didnt find doc for proxy how to start and what settings should be done in player of example 

Is it okay what I am doing as I cant see its working I must be missing something

1) downloaded repo started file https://github.com/Streamedian/html5_rtsp_player/blob/master/Server(NodeJS)
as node filename from cmd
2) started webserver by python -m SimpleHTTPServer for example folder
3) open index.html of example file


Thanks
