### ISSUE TITLE
ERROR in The node API for `babel` has been moved to `babel-core`.

### ISSUE THREAD

**Issue by waiter89** [Streamedian/html5_rtsp_player#19]
I am sorry,I am newer to nodejs,

zhuwt@ubuntu:~/rtsphtml/node_modules/html5_rtsp_player/examples$ webpack --config webpack.config.js
Hash: c848527f64a5353b8e14
Version: webpack 1.13.2
Time: 87ms
    + 1 hidden modules

ERROR in The node API for `babel` has been moved to `babel-core`.

what should I do?

**Comment by karolmajek** [comment]
These two lines solve the problem, but there is another...
sudo npm uninstall babel --save-dev
sudo npm install babel-loader babel-core --save-dev

webpack --config webpack.config.js
Hash: c848527f64a5353b8e14
Version: webpack 1.13.3
Time: 217ms
    + 1 hidden modules

ERROR in ./test.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "./tmp/node_modules/html5_rtsp_player"

**Comment by karolmajek** [comment]
Linked with issue #5

I've made npm install bp_event bp_logger bp_statemachine in html5_rtsp_player and in example
And I still have problem with es2015

Can you update readme with step by step instructions how to run example on new ubuntu installation (you can use vm e.g. from osboxes.org)?

**Comment by kreopt** [comment]
Version you are using is obsolete now. You can try new version of player with rollup bundler and simply add buble plugin to it's config. Note that new player version requires new proxy that can be downloaded from http://streamedian.com/

**Comment by samueosborn** [comment]
in your **webpack.config.js** file make the **loader** be **loader:babel-loader** and it would work. no need to uninstall

    module:{
        loaders:[
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                exclude: /node_modules/
            }
        ]
    }
