### ISSUE TITLE
Standalone websocket video player?

### ISSUE THREAD

**Issue by Victordmdb** [Streamedian/html5_rtsp_player#21]
Can the websocket player work on its own? As in could one open a ws connection with a server, after which the server would start writing to the ws, perhaps for example an ffmpeg stream?

This would play in well with the future [Full Duplex DASH Specification](http://www.iso.org/iso/home/store/catalogue_tc/catalogue_detail.htm?csnumber=71072)

**Comment by Victordmdb** [comment]
Something similar to [this project](http://phoboslab.org/log/2013/09/html5-live-video-streaming-via-websockets) but extended to more formats the mpeg1

**Comment by kreopt** [comment]
Technically it can be done but is not supported yet. You can implement protocol described in readme page on your server to achieve desired result or fill feature request at http://streamedian.com
