### ISSUE TITLE
How can I play rtsp stream with brower?

### ISSUE THREAD

**Issue by ShawZG** [Streamedian/html5_rtsp_player#23]
I finish installing the server side and brower side. 
when I run "sudo  service ws_rtsp start", there is nothing to display. Is it OK ?

the command "netstat -ltn" only display : 
shaw@ubuntu:~/workspace/proxy$ netstat -ltn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN 

and when i open the index.html with firefox, 
![image](https://cloud.githubusercontent.com/assets/22807878/20510488/8ed277ec-b0ab-11e6-9f94-ecb20ee5096d.png)

Does proxy work correctly ?

**Comment by ShawZG** [comment]
***test.js file context :***
import {LogLevel} from 'bp_logger';
import * as rtsp from 'rtsp/rtsp_player';

rtsp.RTSP_CONFIG['websocket.url'] = "ws://127.0.0.1:8080/ws";

document.addEventListener("DOMContentLoaded", function() {
    setTimeout(()=> {
        let player = rtsp.attach(document.getElementById('test_video'));
        if (!player.started()) {
            player.start();
        }
    }, 200);
});

***index.html file context:***
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HTML5 RTSP player example</title>
    <style>
        #test_video {
            width: 720px;
        }
    </style>
</head>
<body>
<video id="test_video" controls autoplay src="rtsp://xxx.xxx.xxx.xxx/RTStream/cam55163_url2_copy.sdp"></video>
<script src="test.bundle.js"></script>
</body>
</html>

**Comment by kreopt** [comment]
could you try latest player and proxy version from http://streamedian.com and tell if problem is gone?
