### ISSUE TITLE
rtsp/rtsp_player module

### ISSUE THREAD

**Issue by tooog** [Streamedian/html5_rtsp_player#27]
i can't find rtsp/rtsp_player module
![error1](https://cloud.githubusercontent.com/assets/24976551/21742721/01cdb796-d52f-11e6-8a84-74e7a7e06a89.PNG)
![error2](https://cloud.githubusercontent.com/assets/24976551/21742723/09ec20fc-d52f-11e6-8ee5-3e750cd82ca1.PNG)

**Comment by kreopt** [comment]
please try new version of our player. branch you are using is not supported anymore
