### ISSUE TITLE
Lag of at least 5 seconds and sometimes it crash/freeze.

### ISSUE THREAD

**Issue by mburger81** [Streamedian/html5_rtsp_player#28]
We are using your html5_rtsp_player to stream an rtsp stream over the html5 video tag, and this is working fine.

But we have two problems.
The video has at least 5 seconds of lag if we compare it to a flash player.
And the other problem is, sometimes it crashes or freeze but without any errors on the console.

Can you help?

**Edit:**
I go ahead with investigation, I added control to video and see that the stream is always downloading but the player/browser is pausing for 2 or 3 seconds, so the player is behind the live stream. On go to the end of the stream by the navigation bar I'm back at the end of the stream with 1 second of lag comparing to the flash player.
Firefox has many more problems, so there are more pausing events and so the player in firefox after 1 hour is behind several minutes after that time period. See below the screenshot of how it looks in firefox.

Usually when the player has this problems in the log I see this:
**broken chunk (continuation of frame with other timestamp)  rtsp_player.js:1771:19
broken chunk (continuation of lost frame)**

I use the js file downloaded from your demo site
https://specforge.com/html5playerstream/index.html

![image](https://cloud.githubusercontent.com/assets/3778892/21935025/11d00988-d9ac-11e6-991c-984a155259b2.png)

**Comment by kreopt** [comment]
please, try new version of our player and proxy from http://streamedian.com and tell if lags are gone.
