### ISSUE TITLE
only unicast or also multicast support?

### ISSUE THREAD

**Issue by Djfe** [Streamedian/html5_rtsp_player#29]
Am I right for assuming, that this "player" only supports unicast streams? (If not I would be glad, multicast isn't used widely enough after all)

**Comment by kreopt** [comment]
Player connects with proxy with point-to-point websocket protocol. So, no. There is no multicast from our proxy. But  from other hand, technically our proxy can listen multicast streams (but it is not tested and likely not supported at the moment)

**Comment by Djfe** [comment]
ok thx for your answer :) 
it's a shame modern browsers don't support multitasking/upnp/Transportstreams yet.
could save the streaming services big amounts of money and stabilize the streams
