### ISSUE TITLE
Source for ws-rtsp-proxy or blob compiled for different architectures (ARM)

### ISSUE THREAD

**Issue by r4** [Streamedian/html5_rtsp_player#30]
I'm trying to get ws-rtsp-proxy working on a raspberry pi but the blob within the debian/ubuntu and rpm packages are not for ARM processors.

Could you provide the source so we can compile for different architectures or can you provide compiled versions for different architectures?

It would also be helpful if this was hosted github (or somewhere) so other Linux distros could integrated this SW into their respective package management tools.

Thanks,
-Drew

**Comment by kreopt** [comment]
We're have no plans to open source of our websocket proxy at the moment. It can be relatively easily compiled for different architectures. Fill feature request at http://streamedian.com for it

**Comment by peterkhang** [comment]
I have also same issue.

I'm trying to set up ws-rtsp-proxy on Mac.

It would be helpful to me if I could get the source!!!

Thank you in advance
-Peter Khang
