### ISSUE TITLE
Some streams does not automatically start on Firefox

### ISSUE THREAD

**Issue by jelqui** [Streamedian/html5_rtsp_player#31]
Plays video  on Chrome but not on Firefox the error log is "unreachable code after return statement[[Learn More]](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Stmt_after_return)" test.bundle.js:2812:13 
Note: Play video without audio on Chrome on Firefox not video not even audio

**Comment by kreopt** [comment]
Could you tell what OS and Firefox version are you using? Can not reproduce bug.

**Comment by kreopt** [comment]
fixed
