### ISSUE TITLE
Problems downloading sources

### ISSUE THREAD

**Issue by StefanRu1** [Streamedian/html5_rtsp_player#32]
Hi,
i followed the wiki but when i try to install:
npm install bp_event bp_log bp_statemachine
i get:
npm ERR! Linux 4.4.38-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bp_event" "bp_log" "bp_statemachi             ne"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/bp_log
npm ERR! 404
npm ERR! 404 'bp_log' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

Also when trying to install:
wget http://repo.tom.ru/deb/debian/non-free/all/ws-rtsp-repo-1.2.deb 
i get:
wget http://repo.tom.ru/deb/debian/non-free/all/ws-rtsp-repo-1.2.deb
--2017-02-14 19:28:23--  http://repo.tom.ru/deb/debian/non-free/all/ws-rtsp-repo-1.2.deb
2017-02-14 19:28:23 FEHLER 404: Not Found.

Is it outdated?

I hope someone can help me, i searched for this solution a long time.

Thanks,
Stefan

**Comment by kreopt** [comment]
It's a typo. Try bp_logger instead of bp_log.
As for ws-rtsp-repo: it is now outdated. Use new proxy version from http://streamedian.com

**Comment by StefanRu1** [comment]
Thank you! This worked now.

But the next problem i face i sthe command "rollup -c"
This does not work. I putted the file rollup.config.js as described in my home directory and called the command "rollup -c".
But i get a command not found. ( I also tried with webpack but also command not found. )
What am i missing here?

Thanks again,
Stefan

**Comment by kreopt** [comment]
You should install rollup with 
`> npm install -g rollup`

> Is it even possible to do this on the raspberry?
Only x86_64 architecture is supported for a moment. To request builds for other platforms fill form at http://streamedian.com
