### ISSUE TITLE
ipcam streaming 

### ISSUE THREAD

**Issue by blasheroy** [Streamedian/html5_rtsp_player#35]
Hello community, 
I am using the Arecon VIsion ipcam with rtsp url 'rtsp://192.168.1.210/h264.sdp?res=full&x0=0&y0=0&x1=800&y1=600&qp=20&ratelimit=10000&doublescan=0&ssn=31817'. 
The socket used is 'wss://127.0.0.1:8080/ws/'
The video cannot be displayed on the browser no matter Google Chrome or Firefox.  
The error shown are 
" GET rtsp://192.168.1.210/h264.sdp net::ERR_UNKNOWN_URL_SCHEME
websocket.js:240 WebSocket connection to 'wss://127.0.0.1:8080/ws/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
Promise @ websocket.js:240
connect @ websocket.js:239
disconnect.then @ websocket.js:56
logger.js:36 [transport:ws] [ctrl] error
_log @ logger.js:36
error @ logger.js:45
ctrlChannel.onerror @ websocket.js:294
logger.js:36 [transport:ws] [ctrl] close. code: 1006 unknown reason "
![screenshot from 2017-03-23 02-53-15](https://cloud.githubusercontent.com/assets/18228712/24194340/a5f35db8-0f30-11e7-8cd1-8376e5501821.png)

**Comment by kreopt** [comment]
I see that you are using wss:// protocol for connecting to websocket proxy. It is not supported now by our server. You have to use some proxy server like nginx to handle ssl connections and pass them in plain mode to our server.

**Comment by blasheroy** [comment]
In case i want to use ws:// protocol, is it necessary to use the proxy server to pass the rtsp stream from the ipcam to the html display?

**Comment by kreopt** [comment]
Yes, proxy is necessary because browsers can't drectly connect to raw TCP endpoints so we need to wrap rtsp/rtp stream into websocket messages, which is exactly what our websocket rtsp proxy does
