### ISSUE TITLE
How to use the example?

### ISSUE THREAD

**Issue by maxdylan** [Streamedian/html5_rtsp_player#36]
I just change the url in the example, but it's not work. How to use the example? and I really don't know how to use the npm and rollup, so I want to know the example can used or not...

**Comment by kreopt** [comment]
You should install our proxy from https://streamedian.com and can specify websocket url in streamedian.js:9316 if you stream located in local network. 
If stream is in global network substituting rtsp url should work. If not, please attach browser logs

**Comment by maxdylan** [comment]
Is the url must be a global url? In fact, I want to construct a local environment to show the camera view in my phone, can it work? Thank you for your answer very much.

**Comment by victorgrenke** [comment]
yes you can use instead of global url your local ip address


28.03.2017 12:43, WhichHuo пишет:

**Comment by kreopt** [comment]
Note that for using local stream addresses, you should download and install streamedian websocket proxy from https://streamedian.com on your server. it will wrap your rtsp streams into websocket protocol to allow playing it in browser

**Comment by maxdylan** [comment]
Thank you very much
