### ISSUE TITLE
RTSP type h264 can't play

### ISSUE THREAD

**Issue by ChampsReprobate** [Streamedian/html5_rtsp_player#4]
Hello 

I create rtsp proxy server on fedora 23 server and test rtsp type mp4 it ok, but when i test by rtsp type by h264 it can't play for me 

Please tell me what i wrong config

Thanky everyone

**Comment by victorgrenke** [comment]
hello 

It's not enought information please explain it 
give me your the config code to understand what you do

**Comment by ChampsReprobate** [comment]
Thank you @victorgrenke   for reply

Ok. first I Create vmware and install fedora server 23 and then i install ws_rtsp_proxy,
I config port 8015 and run command service ws_rtsp start

and i create html5 file for client and use test.bundle.js from http://specforge.com/html5playerstream/index.html and change websocket from my websoceket
ps. url test is ="rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov"

and test run oh.it ok can play lok so good
then after i change url it real ipcamera = "rtsp://view:1234567@xx.xx.xx.xx:1554/h264/ch3/sub/av_stream"

it can't play me i dont know how to check what i wrong 

Please tell me 

Thank you for everyone

**Comment by victorgrenke** [comment]
Hello 

At current version our player is not supporting user:password link
Try the camera without user password.

Some latter we support it.

**Comment by ChampsReprobate** [comment]
Hello @victorgrenke 

thank you for reply

I will waiting

Thank you

**Comment by tsingyee** [comment]
Also waiting for this feature.
It would help a lot if supports username/password in the url.

**Comment by tsingyee** [comment]
@ChampsReprobate I just found that the underlying RTSPConnection of rtsp/connection.js support username/password authentication. however, RTSPPlayer of rtsp_player.js doesn't pass the username/password to RTSPConnection constructor.

![image](https://cloud.githubusercontent.com/assets/8817111/17382515/1d129eb0-5986-11e6-9a1b-2914289e3dcc.png)

you can fix it like below and re-pack your test.bundle.js:
![image](https://cloud.githubusercontent.com/assets/8817111/17382540/438b1324-5986-11e6-92c2-b253f58b8113.png)

**Comment by ChampsReprobate** [comment]
Thank you verymuch for this , I will test it  Thank you

**Comment by victorgrenke** [comment]
For the current version of player I included your changes, thank you.

Authorization of flows (to proxy side and player) is also supported in new version
It will be posted on GitHub as soon as all current problems with proxy infrastructure will be solved, 
because new version works with proxy, backward incompatible that now is in repository.

**Comment by ferglezt** [comment]
Hello. I'm experimenting a similar issue. I can't get stream with a URL like "rtsp://192.168.xx.xx:554/cam/realmonitor?channel=CHANNEL&subtype=ENCODING&authbasic=USER:PASS_BASE_64" This works well with VLC media player and VXG Chrome plugin, but I can't get any stream from the proxy.

The proxy works fine with the url "rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov" though.

Any ideas on how to make it work? Thanks!

**Comment by tsingyee** [comment]
@ferglezt maybe you can try: rtsp://{User}:{PlainPassword}@192.168.xx.xx:554/xxxxxx

**Comment by ferglezt** [comment]
@tsingyee I just tried urls like:

rtsp://user:pass@192.168.xx.xx:554/cam/realmonitor?channel=1&subtype=00
rtsp://user:pass@192.168.xx.xx:554/cam/realmonitor
rtsp://user:pass@192.168.xx.xx:554/

But still not getting any results. I don't know the reason why I can't catch any stream here, but VLC and VXG plugin work fine. Thanks!

**Comment by kreopt** [comment]
Fixed in latest version
