### ISSUE TITLE
Unable to stop stream by clientside, Loop 'remux' error

### ISSUE THREAD

**Issue by mburger81** [Streamedian/html5_rtsp_player#40]
We implement your client for our system, but we have some problems to stop the stream.

We use your lib in an angular2 WebApp like that:
```
import WSPlayer from './assets/js/rtsp_player';

@Component({
   ....
})
export class LaRTSPlayerComponent implements AfterViewInit, OnChanges, OnDestroy {
    @Input() streamUrl: string;

    public id: string = 'rtsp-player-' + Math.random().toString(36).slice(2);
    private wsPlayer: any;

     ngAfterViewInit() {
        this.startPlay();
    }

    ngOnDestroy() {
        this.stopPlay();
    }

    private startPlay() {
        this.wsPlayer = new WSPlayer(this.id, {socket: this.streamUrl, url: 'rtsp://127.0.0.1/', type: 'rtsp'});
    }

    private stopPlay() {
        if (this.wsPlayer) {
            // player is PAUSED also on leaving destroying this component, but I'm not sure which is the best   way to destroy and remove any eventListener
            // so to be secure, I will do this all also manually
            this.wsPlayer.stop();
            this.wsPlayer = null;
        }
    }
}
```

After the component is init we start the Play by creating a new instance of `WSPlayer`, the player start playing the stream and works very good. We see the log `Client started`

The problem is, if we leave the page and so close the player we wan't to stop the play and close stream in the right way.

We try this by call the `stop()` method, and set the instance after that to null.  Calling stop() we see two times the log `Client paused`.
Every thing seems to be fine, but if you wait a wail, you can see the stream does always log stuff to the console, so it seems the stream is not closed at all, and if you wait longer you get error loop, this is our entire log!

```
Client paused
Client paused
broken chunk (continuation of lost frame)
[transport:ws] [ctrl] close. code: 1000 unknown reason ...
[mse] video/mp4; codecs="avc1.42001f" cleaning start
[mse] Source buffer aborted: closed
[mse] video/mp4; codecs="avc1.42001f" cleaning end
[mse] Media source ended: closed
[mse] Media source closed: closed
[mse] Media source opened: open
Client started
ERROR TypeError: Cannot read property 'remux' of undefined(…)
ERROR TypeError: Cannot read property 'remux' of undefined(…)
ERROR TypeError: Cannot read property 'remux' of undefined(…)
ERROR TypeError: Cannot read property 'remux' of undefined(…)
ERROR TypeError: Cannot read property 'remux' of undefined(…)
ERROR TypeError: Cannot read property 'remux' of undefined(…)
ERROR TypeError: Cannot read property 'remux' of undefined(…)
ERROR TypeError: Cannot read property 'remux' of undefined(…)
ERROR TypeError: Cannot read property 'remux' of undefined(…)
ERROR TypeError: Cannot read property 'remux' of undefined(…)
```

For any help we are very grateful!!!

**Edit:**
After a lot of errors, they stopped. But also some times after it is possibile the stream comes up again, but I'm not on the page! The problem is, the stream is never closed!

**Comment by kreopt** [comment]
if you need to completely destroy player, try using destroy() method from latest commit. Note that it asynchronous and should be awaited.

**Comment by mburger81** [comment]
Hi @kreopt first of all thx for your fast response.

The problem is, we wasn't able to integrate your github project into our project, not before and also not now. We copied always your test.bundle.js from your demo site.
So we are still on a old old version of your great lib and not the last one. If we copy your few lines of code of your last commit we got some errors, probably there are two big changes, or something that is not existing.

If we include your last github doing  `npm install git://github.com/Streamedian/html5_rtsp_player.git --save` there is now player.js included in `node_modules/ws` folder.

We are sorry but we are really not able to understand your readme.txt and how we can install your client/server. So the only thing we was able to do a long time ago was copying your client from demo site.

Do you think you can help as a little bit?

We are using your lib in a angular2/typescript project.

**Comment by kreopt** [comment]
Don't Typescript work with async/await using regenerator? It can be easily transpiled with something like buble or babel.
I'll update project and example bit later and prepare transpiller for es5-only usage.

**Comment by mburger81** [comment]
The problem is frameworks like ionic does not support transpiling to es5 in developement mode, this is to slow for dev. 
Can I asko you what do you intend with "bit later"  :) 
I forked your repo and will check if we can do transpiling by our own, and if we can resolve the import issues. But for sure it would be better if you are able to do this :p

**Comment by kreopt** [comment]
bit later = this week but no idea when exactly:)
Updated Readme and example a bit. Could you tell what is unclear in Readme so I can fix it?

**Comment by mburger81** [comment]
Sorry for my very late response! But I we was out of office for a while for installation. And I wasn't able to test it.

Are you sure about the `import * as streamedian from 'streamedian/player.js';`
After doing `npm install git://github.com/Streamedian/html5_rtsp_player.git -save` there is now `player.js` file located into node_modules/streamedian folder.

**Comment by mburger81** [comment]
Hi, I would like to ask you if there are some news about the issue and your intention to prepare transpiler for es5-only usage?

thx

**Comment by kreopt** [comment]
Hi, still no news about this issue and not sure when it will be finished

**Comment by kopagana** [comment]
we also tried to use your player on angular-cli project.
Is there any news on the `destroy()` case?
for now, when the component that was importing the `js` code is destroyed we entering an infinite loop
for `[transpotrts:ws] got data`  
thanks a head :)
