### ISSUE TITLE
RTSP in Node.js server in windows 10

### ISSUE THREAD

**Issue by nadbadg** [Streamedian/html5_rtsp_player#44]
Hi ,
I installed the html5_rtsp_player in Node.js server in windows 10. When i run the sample html (index.html) , i am able to recieve the data packets in the server but the video displayed in the video control in my html is broken .I can only see top part of video and rest is  black screen  , even though the video is playing. Could you please help me out to find the solution?

**Comment by nadbadg** [comment]
![html5rtsp](https://user-images.githubusercontent.com/18024920/28247471-317d3e78-6a42-11e7-89a3-5628bb112ad9.JPG)

**Comment by kreopt** [comment]
Could you show browser log? Especially, SDP part? It may be some problems with support of your variant of codec.
And I'm not sure that node server is 100% correct cause it was implemented out of our organization and was not fully checked.

**Comment by nadbadg** [comment]
Hi , Please see the logs obtained from Chrome browser.

[localhost-1500208607121.txt](https://github.com/Streamedian/html5_rtsp_player/files/1151012/localhost-1500208607121.txt)

**Comment by kreopt** [comment]
looks like something wrong with your stream (chrome throws errors). I'll look deeply tomorrow

**Comment by kreopt** [comment]
could you enable RTSP debug log and show me browser logs again?

You should set log level

getTagged("client:rtsp").setLevel(LogLevel.Debug);

at streamedian.js:9124 if you are using prebuilt example

**Comment by nadbadg** [comment]
Hi , I added the debug levl loggin see pic below , but the logs seems to be the same.
![image](https://user-images.githubusercontent.com/18024920/28265313-2e8f0ee4-6b00-11e7-8502-539bf8dd199c.png)
New log file :
[localhost-1500289033895.txt](https://github.com/Streamedian/html5_rtsp_player/files/1152293/localhost-1500289033895.txt)
Also note i am running the server in Windows Node.js , Thanks
