### ISSUE TITLE
H264 Main Profile support

### ISSUE THREAD

**Issue by gregpabian** [Streamedian/html5_rtsp_player#47]
Hi, I've been working on your player extensively to enable direct playback of RTP stream delivered over WebSocket (no negotiation phase, just immediate playback after passing the SDP). I can see all the RTP packets are coming in order and the audio decodes perfectly fine. I've noticed, however, that the player has some troubles when trying to play a live video stream compressed using H.264 Main profile, while the one compressed with H.264 Baseline profile works just fine.

Here's an SDP for the Baseline profile compressed stream:
```
v=0
o=- 1953854714 1953854714 IN IP4 127.0.0.1
s=greg
c=IN IP4 0.0.0.0
t=0 0
a=sdplang:en
a=range:npt=now-
a=control:*
m=audio 0 RTP/AVP 96
a=rtpmap:96 mpeg4-generic/44100/1
a=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1208
a=control:trackID=1
m=video 0 RTP/AVP 97
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=1;profile-level-id=42801F;sprop-parameter-sets=Z0KAH5ZSAKALdgKhAAADAAEAAAMAPOBgAHoSAAEYw/xjjAwAD0JAACMYf4xw7QoVJA==,aMuNSA==
a=cliprect:0,0,720,1280
a=framesize:97 1280-720
a=framerate:30.0
a=control:trackID=2
```
This one plays smooth both in my custom implementation and yours using the Node.js proxy.

And here's the Main profile one:
```
v=0
o=- 229000092 229000092 IN IP4 127.0.0.1
s=greg
c=IN IP4 0.0.0.0
t=0 0
a=sdplang:en
a=range:npt=now-
a=control:*
m=audio 0 RTP/AVP 96
a=rtpmap:96 mpeg4-generic/44100/1
a=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1208
a=control:trackID=1
m=video 0 RTP/AVP 97
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=1;profile-level-id=4D401F;sprop-parameter-sets=Z01AH5ZSAKALdgKhAAADAAEAAAMAPOCgAHoSAAEAWfxjjBQAD0JAACALP4xw7QsWyQ==,aOtzUg==
a=cliprect:0,0,720,1280
a=framesize:97 1280-720
a=framerate:30.0
a=control:trackID=2
```
The second one, even though it seems to play something, is full of artifacts and happens to freeze after a couple of seconds. I've also noticed a much bigger CPU use on Chrome (65% on main profile vs. 15%  baseline).

Another thing I've noticed is that in H.264 Main profile compressed streams, there's much more STAPs that currently get ignored completely.

So, my questions are:
1. Is your player supposed to support H.264 main profile content?
2. Do you have any plans to improve the compatibility/performance for such streams? 
3. Are the any additional information I could provide that would help you investigate what's wrong with remuxing of such a video?
4. Do you think that STAP-A traffic that's ignored at the moment might be significant in this case and should be processed and pushed to samples queue?

Thanks for this interesting project, I hope you'll keep working on it!

**Comment by kreopt** [comment]
Hi! 
1. Technically, player support every h264 profile content, supported by browser as it just remux stream into browser-readable format. 
2. So, decoding performance is highly depends on how browser decode the video. Although, we have plans to increase remuxer performance to reduce latency sometimes in future. As a suggestion, you can make sure that you have hardware decoding enabled in your browser so it can help with CPU usage. 
3. You can give you stream url with main profile for testing purposes. We had tested some streams with main profile and it was ok.
4. probably yes, but should be checked
