### ISSUE TITLE
RTSP is not defined

### ISSUE THREAD

**Issue by shinjiDev** [Streamedian/html5_rtsp_player#48]
Hi
I'm trying to follow the steps of https://github.com/Streamedian/html5_rtsp_player/wiki/HTML5-RTSP-Player (It must be updated)
After a long work, I'm really close to have my rtsp player, but I received the next console error:
Uncaught ReferenceError: rtsp is not defined
    at example.js:5

let mediaElement = rtsp.attach(document.getElementById('test_video'));

Could you help me to solve this issue?

Regards

Edit: By the way, I just want to use the player functionality, I don't want the websocket in the serverside.

**Comment by kreopt** [comment]
Hi
Try to use example/streamedian.js

example.js in root folder is outdated. I'll remove it

**Comment by kreopt** [comment]
where did you get example with 

let mediaElement = rtsp.attach(document.getElementById('test_video'));

line?

It is outdated and removed from main repository

**Comment by shinjiDev** [comment]
@kreopt the line and all the guide is in the link:
https://github.com/Streamedian/html5_rtsp_player/wiki/HTML5-RTSP-Player

Should I follow another start guide?

**Comment by shinjiDev** [comment]
@kreopt I tried using the "example.js" from the main repository, but it doesn't work for me.

**Comment by shinjiDev** [comment]
I've tried using the example/streamedian.js. I receive these errors:
Client paused
logger.js:36 Client started
index.html:1 Not allowed to load local resource:
blob:null/ee91058b-d7b2-48a4-8032-e9b10304ad3f
websocket.js:247 WebSocket connection to 'wss://specforge.com/ws/' failed:
Error during WebSocket handshake: Unexpected response code: 502
Promise @ websocket.js:247
connect @ websocket.js:246
disconnect.then @ websocket.js:63
logger.js:36 [transport:ws] [ctrl] error
_log @ logger.js:36
error @ logger.js:45
ctrlChannel.onerror @ websocket.js:301
logger.js:36 [transport:ws] [ctrl] close. code: 1006 unknown reason

I just want to stream my RTSP.

Regards

**Comment by kreopt** [comment]
wss://specforge.com/ws is not very stable place to test cause it is public and can be temporary unavailable. It is better to get your copy of proxy and test locally.

**Comment by williegreat** [comment]
Does anybody complete streamedian.js sample with RTSP ?
If yes, can you share the code please?

**Comment by victorgrenke** [comment]
> Does anybody complete streamedian.js sample with RTSP ?
What do you mean?

**Comment by williegreat** [comment]
I've followed the instructions on Stremeadian page and struggled on a Server Side : 
Server side

Install websocket proxy

**Sign up and install websocket proxy from http://streamedian.com

Register domain you want to use this player

Download license file to your server**

Note that this package depends on systemd and gcc5+ runtime so it can be installed only on recent distribution versions.

Configure port and license file path in /etc/ws_rtsp.ini

This port should be open in your firewall. Also you can pass request to this port from your proxy. (for example: http://nginx.org/en/docs/http/websocket.html)

Run it

**Comment by williegreat** [comment]
I mean if somebody has already done that, can you supply a server side code ?
I want to test it locally

**Comment by sheldonanto** [comment]
Any possible way to change the http port number
