### ISSUE TITLE
How can I run the example

### ISSUE THREAD

**Issue by BMo-design** [Streamedian/html5_rtsp_player#5]
Hi,
I want to use your script to show the stream of my Xioami YI cam. 
However, I guess I need some help to rund your code.

I downloaded your files with the "npm install git://github.com/SpecForge/html5_rtsp_player.git" command.
Then I navigated to the example folder in my terminal and executed "npm install".
However, "npm install bp_event bp_log bp_statemachine" does nor work. There seems to be a problem with bp_log. I installed bp_logger instead.

Next, "webpack --config webpack.config.js" -> throw the error "ERROR in ./test.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory... ".

What do I have to do to compile your example?

**Comment by victorgrenke** [comment]
Hello

could you try to make  
>npm install 
in "html5_rtsp_player" folder

it seems to me it should work

let me know the result please

**Comment by mburger81** [comment]
Hi @BMo-design, was you able to get it work?

We are trying to implement the lib in our project but there are several problems, as you we are not able to build the test.build.js file.

Some infos or code to share with us?

**Comment by szhansen** [comment]
hi,anybody can send me the file:  webpack.config.js
94022640@qq.com
thanks a lot.
![image](https://cloud.githubusercontent.com/assets/11768216/22063781/a8a63ff4-ddbb-11e6-9143-f8d2622c3609.png)

**Comment by kreopt** [comment]
all necessary files are in repository now
