### ISSUE TITLE
MediaSource readyState === closed

### ISSUE THREAD

**Issue by mburger81** [Streamedian/html5_rtsp_player#50]
I tried your latest player on github and we have some problems with MediaSource. On first launch of player the new MediaSource instance in MSE has always as readyState closed and the player does not start playing the video.

![image](https://user-images.githubusercontent.com/3778892/30326993-c46e31c8-97ca-11e7-847b-76b0b12feb73.png)

In this case we get an error on video tag error listner:
`MediaError code:4 message: MEDIA_ELEMENT_ERROR: Unable to attach MediaSource`

![image](https://user-images.githubusercontent.com/3778892/30326971-b251d292-97ca-11e7-9b4e-7f412dc4e012.png)

If we reload the page with F5 anything is fine, the MediaSource readyState is open and the player plays the stream

**Comment by mburger81** [comment]
Sorry it is not the latest but the player in version 0.3.4

**Comment by mburger81** [comment]
This error is still present on 0.3.8
@kreopt can you please jump into this issue, if you can help me a little bit we can go ahead on checking the issue. We are at a point we can not discover on which could be the reason for the issue.
Give as some hints and we will try to get some workaround and a PR fot his problem
thx

**Comment by victorgrenke** [comment]
this error is in the last code?
