### ISSUE TITLE
how to install websock_rtsp_proxy on CentOS7.1?

### ISSUE THREAD

**Issue by hkxiaohu** [Streamedian/html5_rtsp_player#52]
My OS is CentOS7.1 x86-64, I have downloaded the streamedian_proxy.deb from the following link (https://streamedian.com/cabinet/#)
When I try dpkg –I streamedian_proxy.dep, a lot of package is missing: ibboost-filesystem1.58.0、 libboost-system1.58.0，libboost-program-options1.58.0
，libc6，libgcc1，libstdc++6， system.
Is there any way that we can install websock_rtsp_proxy on CentOS7.1 ?? 
We have noticed that “Note that this package depends on systemd and gcc5+ runtime so it can be installed only on recent distribution versions.”, would you please tell me which version of systemd do I need?

**Comment by kreopt** [comment]
Hi! 
1. you should install gcc5 or greater (you can install devtoolset-4 or greater)
2. get boost and compile it from sources then install it

systemd version does not matter. It just should be

**Comment by hkxiaohu** [comment]
thank you very much~ It helped me a lot
