### ISSUE TITLE
Cannot run your demo

### ISSUE THREAD

**Issue by hnptvtoan** [Streamedian/html5_rtsp_player#53]
Hey ,
I can't run your demo with url rtsp example (rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov) with log:[mse] Error occured: error occurred when decoding.
How to me can run your demo with url rtsp example.
Thanks you!

**Comment by mburger81** [comment]
Hi I'm not the owner of the project.
Do you need there WebSocket Proxy, did you install it and proxy over it? This is for now not a standalone player where you can call direkt the rtsp stream if you are trying to do this

**Comment by kreopt** [comment]
Fixed in latest version. Although, there is an issue with this stream(and possibly other streams than not starts with IDR packet) in firefox: playback will not start until timeline is seeked forward by 1 second
