### ISSUE TITLE
Version 0.3.8 doesn't dispatchEvent 'ready'

### ISSUE THREAD

**Issue by mburger81** [Streamedian/html5_rtsp_player#55]
Hi @kreopt @victorgrenke 
We use your latest 0.3.8 where we don't see any VIDEO played in <video> tag.

It is difficult to figure out the problems, because we are not an expert on video and on your lib.

But we figured out Remuxer is never init because in flush() method there is never fired the dispatchEvent('ready').
On you last version we used which should be 0.3.5 anything is fine. So our question is what did you changed or what is causing this problem?

please help
thx

**Comment by mburger81** [comment]
in flush method there is always this true
`if (!this.tracks[track_type].readyToDecode || !this.tracks[track_type].samples.length) return;`
and so dispatchEvent('ready') is never fired

**Comment by mburger81** [comment]
Ok I figured our the problem!!!
We have the problem in the `H264Remuxer` with the new `remux()` method
If we uncomment the nalu.toString() log we got this output
NDR: NRI: 1, PTS: -1506046017672, DTS: -1506046017672
NDR: NRI: 1, PTS: -1506046014072, DTS: -1506046014072
NDR: NRI: 1, PTS: -1506046010472, DTS: -1506046010472
NDR: NRI: 1, PTS: -1506046003272, DTS: -1506046003272
NDR: NRI: 1, PTS: -1506045999672, DTS: -1506045999672
NDR: NRI: 1, PTS: -1506045996072, DTS: -1506045996072
NDR: NRI: 1, PTS: -1506045992472, DTS: -1506045992472
NDR: NRI: 1, PTS: -1506045985272, DTS: -1506045985272

so as you can see `DTS` is less then `0`, but the default `lastGopDTS` is set to `0` so this
`if (this.lastGopDTS < nalu.dts) {`
is never `true`.
if we set `lastGopDTS` to `-99999999999999` anything is fine.

So honestly we have no idea what is `NALU` and what is `DTS`, but this workaround does work for us.
If you like I can do a **PR**?

**Comment by kreopt** [comment]
Hi! All pull requests and bug reports are welcome! Thanks for investigation
the root of this problem. We'll look deeply and fix things as soon as it
will be possible.

22 сент. 2017 г. 21:22 пользователь "mburger81" <notifications@github.com>
написал:

**Comment by mburger81** [comment]
we created a PR for this issue #56
