### ISSUE TITLE
Can I use standalone as javascript version?

### ISSUE THREAD

**Issue by MinChanSike** [Streamedian/html5_rtsp_player#58]
How can I use standalone javascript version embedded in html file?

```
<body>
        <video id="test_video" controls autoplay src="rtsp://your_rtsp_stream/url"></video>
        <script src="streamedian.js"></script>
</body>
```

**Comment by mburger81** [comment]
Hi, I'm not the owner of the project but I think you can answer your question.
The player as it is is not usable as standalone player you have to use there WebSocket proxy. But we have altered it and we are using it without there Proxy with a custom WebSocket Server which is encapsulating the RTSP stream in a WebSocket stream ...

**Comment by MinChanSike** [comment]
How it is? Can I get reference source?

**Comment by mburger81** [comment]
We can share our code with you but first I have some questions. In which project do you like to use this library? Do you have experience with RTSP and VIDEO streams?
The player is working for the most part good, but on the other side there are some problems. Do you think you can help?

**Comment by MinChanSike** [comment]
Thanks, I will play live RTSP Video Stream from Wowza Engine.
It is possible to play Wowza RTSP stream?

**Comment by kreopt** [comment]
Wowza streams are supported but not well tested. You can try latest player version
