### ISSUE TITLE
bp_log cannot be installed.

### ISSUE THREAD

**Issue by guanxingquan** [Streamedian/html5_rtsp_player#6]
sudo npm install bp_log 
this command cannot work.
npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "bp_log"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/bp_log
npm ERR! 404 
npm ERR! 404  'bp_log' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/html5_rtsp_player/npm-debug.log

OS: ubuntu 16.04 
what I missed ?

**Comment by victorgrenke** [comment]
it's typo. in the readme changed bp_log on bp_logger
