### ISSUE TITLE
How to support multiple views on one page?

### ISSUE THREAD

**Issue by wangbinkaisquare** [Streamedian/html5_rtsp_player#64]
I tried multiple view on one page but only one can work, if need view more then how can I do it, thanks.

**Comment by kreopt** [comment]
You can instantiate new player like this (append this to example.js and build it with rollup):

```
...
let player = new streamedian.WSPlayer(videoElementId, {
    modules: [
        {
            client: RTSPClient,
            transport: wsTransport
        }
    ],
    ...
});
```
