### ISSUE TITLE
when send PLAY ,error : session not found

### ISSUE THREAD

**Issue by btshj** [Streamedian/html5_rtsp_player#65]
Client paused
streamedian.min.js:281 Client started
streamedian.min.js:281 [transport:ws] WSP/1.1 INIT
proto: rtsp
host: 10.0.10.68
port: 554
seq: 1

streamedian.min.js:281 [transport:ws] [ctrl]
WSP/1.1 200 OK
seq: 1
channel: localhost-2 342128387

streamedian.min.js:281 [transport:ws] WSP/1.1 JOIN
channel: localhost-2 342128387
seq: 2

streamedian.min.js:281 [mse] Media source opened: open
streamedian.min.js:281 [transport:ws] [data]
WSP/1.1 200 OK
seq: 2

streamedian.min.js:281 [client:rtsp] OPTIONS * RTSP/1.0
CSeq: 1
User-Agent: SFRtsp 0.3

streamedian.min.js:281 [transport:ws] WSP/1.1 WRAP
contentLength: 55
seq: 3

OPTIONS * RTSP/1.0
CSeq: 1
User-Agent: SFRtsp 0.3

streamedian.min.js:281 [mse] Media source ended: closed
streamedian.min.js:281 [mse] Media source closed: closed
streamedian.min.js:281 [transport:ws] [ctrl]
WSP/1.1 200 OK
seq: 3

RTSP/1.0 200 OK
CSeq: 1
Date: Thu, Jan 01 1970 14:37:04 GMT
Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER

streamedian.min.js:281 [client:rtsp] RTSP/1.0 200 OK
CSeq: 1
Date: Thu, Jan 01 1970 14:37:04 GMT
Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER

streamedian.min.js:281 [client:rtsp] DESCRIBE rtsp://10.0.10.68/live RTSP/1.0
Accept: application/sdp
CSeq: 2
User-Agent: SFRtsp 0.3

streamedian.min.js:281 [transport:ws] WSP/1.1 WRAP
contentLength: 102
seq: 4

DESCRIBE rtsp://10.0.10.68/live RTSP/1.0
Accept: application/sdp
CSeq: 2
User-Agent: SFRtsp 0.3

streamedian.min.js:281 [mse] Media source opened: open
streamedian.min.js:281 [transport:ws] [ctrl]
WSP/1.1 200 OK
seq: 4

RTSP/1.0 200 OK
CSeq: 2
Date: Thu, Jan 01 1970 14:37:04 GMT
Content-Base: rtsp://10.0.10.68/live/
Content-Type: application/sdp
Content-Length: 481

v=0
o=- 60257275 1 IN IP4 10.0.10.68
s=live h264 test
i=LIVE555 Streaming Media v2017.09.12
t=0 0
a=tool:LIVE555 Streaming Media v2017.09.12
a=type:broadcast
a=control:*
a=range:npt=0-
a=x-qt-text-nam:live h264 test
a=x-qt-text-inf:LIVE555 Streaming Media v2017.09.12
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:265985
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=4D001E;sprop-parameter-sets=Z00AHpWoKA9puAgICBA=,aO48gA==
a=control:track1

streamedian.min.js:281 [client:rtsp] RTSP/1.0 200 OK
CSeq: 2
Date: Thu, Jan 01 1970 14:37:04 GMT
Content-Base: rtsp://10.0.10.68/live/
Content-Type: application/sdp
Content-Length: 481

v=0
o=- 60257275 1 IN IP4 10.0.10.68
s=live h264 test
i=LIVE555 Streaming Media v2017.09.12
t=0 0
a=tool:LIVE555 Streaming Media v2017.09.12
a=type:broadcast
a=control:*
a=range:npt=0-
a=x-qt-text-nam:live h264 test
a=x-qt-text-inf:LIVE555 Streaming Media v2017.09.12
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:265985
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=4D001E;sprop-parameter-sets=Z00AHpWoKA9puAgICBA=,aO48gA==
a=control:track1

streamedian.min.js:281 [parser:sdp] v=0
o=- 60257275 1 IN IP4 10.0.10.68
s=live h264 test
i=LIVE555 Streaming Media v2017.09.12
t=0 0
a=tool:LIVE555 Streaming Media v2017.09.12
a=type:broadcast
a=control:*
a=range:npt=0-
a=x-qt-text-nam:live h264 test
a=x-qt-text-inf:LIVE555 Streaming Media v2017.09.12
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:265985
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=4D001E;sprop-parameter-sets=Z00AHpWoKA9puAgICBA=,aO48gA==
a=control:track1

streamedian.min.js:281 [parser:sdp] Ignored unknown SDP directive: i=LIVE555 Streaming Media v2017.09.12
streamedian.min.js:281 [parser:sdp] Ignored unknown SDP directive: c=IN IP4 0.0.0.0
streamedian.min.js:281 [parser:sdp] Ignored unknown SDP directive: b=AS:265985
streamedian.min.js:281 [client:rtsp] SDP contained 1 track(s). Calling SETUP for each.
streamedian.min.js:281 [client:rtsp] setup track: video
streamedian.min.js:281 [client:rtsp] SETUP rtsp://10.0.10.68/live/track1 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
Date: Thu, 28 Dec 2017 02:31:16 GMT
CSeq: 3
User-Agent: SFRtsp 0.3

streamedian.min.js:281 [transport:ws] WSP/1.1 WRAP
contentLength: 166
seq: 5

SETUP rtsp://10.0.10.68/live/track1 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
Date: Thu, 28 Dec 2017 02:31:16 GMT
CSeq: 3
User-Agent: SFRtsp 0.3

streamedian.min.js:281 [transport:ws] [ctrl]
WSP/1.1 200 OK
seq: 5

RTSP/1.0 200 OK
CSeq: 3
Date: Thu, Jan 01 1970 14:37:04 GMT
Transport: RTP/AVP/TCP;unicast;destination=10.0.10.103;source=10.0.10.68;interleaved=0-1
Session: A3EF491D;timeout=65

streamedian.min.js:281 [client:rtsp] RTSP/1.0 200 OK
CSeq: 3
Date: Thu, Jan 01 1970 14:37:04 GMT
Transport: RTP/AVP/TCP;unicast;destination=10.0.10.103;source=10.0.10.68;interleaved=0-1
Session: A3EF491D;timeout=65

streamedian.min.js:281 [client:rtsp] PLAY rtsp://10.0.10.68/live/ RTSP/1.0
Session: A3EF491D;timeout=65
CSeq: 4
User-Agent: SFRtsp 0.3

streamedian.min.js:281 [transport:ws] WSP/1.1 WRAP
contentLength: 104
seq: 6

PLAY rtsp://10.0.10.68/live/ RTSP/1.0
Session: A3EF491D;timeout=65
CSeq: 4
User-Agent: SFRtsp 0.3

streamedian.min.js:281 [transport:ws] [ctrl]
WSP/1.1 200 OK
seq: 6

RTSP/1.0 454 Session Not Found
CSeq: 4
Date: Thu, Jan 01 1970 14:37:04 GMT

streamedian.min.js:281 [client:rtsp] RTSP/1.0 454 Session Not Found
CSeq: 4
Date: Thu, Jan 01 1970 14:37:04 GMT

streamedian.min.js:281 [client:rtsp] Session Not Found
value @ streamedian.min.js:281
streamedian.min.js:13 Uncaught (in promise) No such transition: 8 to 1

**Comment by kreopt** [comment]
Hi! Could you try latest version? Is this bug still repeat?

**Comment by Viking1726** [comment]
[transport:ws] [ctrl]
WSP/1.1 200 OK
seq: 6

RTSP/1.0 454 Session Not Found
CSeq: 4
Date: Sat, Jun 09 2018 09:03:11 GMT


streamedian.min.js:282 [client:rtsp] RTSP/1.0 454 Session Not Found
CSeq: 4
Date: Sat, Jun 09 2018 09:03:11 GMT

**Comment by Viking1726** [comment]
yes . I tried it. it's still not work.
