### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by jayasrinagrale** [Streamedian/html5_rtsp_player#66]
I get an error related to https, wss on my browser when I run the demo application

**Comment by huige555551** [comment]
I get the same problem like you

**Comment by victorgrenke** [comment]
Sorry, we are changing the our web site so may be some issues with demo and etc.
https://streamedian.com/demo/free/ - old version of player should work
we are preparing it for new version of player and rtsp restreamer

**Comment by chris-waller** [comment]
Is there any update on when this will be ready to go?

**Comment by kreopt** [comment]
Hi! Could you provide url and logs of broken demo? https://streamedian.com/demo/free/ seems to be working for me.
