### ISSUE TITLE
The demo can run normally but my case did not work

### ISSUE THREAD

**Issue by ZoeZoOo** [Streamedian/html5_rtsp_player#68]
Hi，
   Thank you for your great work with which I can solve my problem. However there are still some troubles. Here is the description.
   **1. Demo works normally**
I use your code from the demo index.html, and use the socket "wss://specforge.com/ws/". I can see the views normally:
![image](https://user-images.githubusercontent.com/36255124/35957075-8c38e6b6-0cd4-11e8-91df-8b4ba87542b1.png)
  **2. Other source shows no view** 
Then I changed the source from "rtsp://127.0.0.1:8554/test"  to rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov, and I just can't see the views, but it seems normal in Console there must some reasons, _**I want to know why?**_
![1](https://user-images.githubusercontent.com/36255124/35957533-01eb2336-0cd7-11e8-8a3c-36c80112627f.png)

  **3. Some errors in my case**
Then I tried to run the proxy service on my ubuntu server and here is the ws_rtsp.ini:
![2](https://user-images.githubusercontent.com/36255124/35957549-0fd373a4-0cd7-11e8-82eb-1eb31fc1d68b.png)
I use the socket "ws://myServerIp:1104" and here is the code:
![3](https://user-images.githubusercontent.com/36255124/35957697-e213b748-0cd7-11e8-83e9-a99d1dda69a3.png)
but when I run it , it would through the error:
![image](https://user-images.githubusercontent.com/36255124/35957682-cef8838c-0cd7-11e8-9983-0bd46d89c253.png)
if I click the "play" button, there would be another error like this:
![4](https://user-images.githubusercontent.com/36255124/35957785-5fc4eeaa-0cd8-11e8-8311-51dcd77f5206.png)
more details about the last error:
![image](https://user-images.githubusercontent.com/36255124/35957928-0b16cf8a-0cd9-11e8-911f-fac32097bd87.png)

**How can I fix it?**
Could you please help me? Thank a lot.

**Comment by kreopt** [comment]
Hi! Please try latest version

**Comment by ZoeZoOo** [comment]
bravo!

I use the laest version of html5_rtsp_player_master to generate the streamedian.js,then I can player the BigBuckBunny

THX for your efforts!
![qq 20180305120406](https://user-images.githubusercontent.com/36255124/36957164-86f78d36-206d-11e8-9f33-6ca701ce67cf.png)
