### ISSUE TITLE
Could not resolve './session'

### ISSUE THREAD

**Issue by fast0490f** [Streamedian/html5_rtsp_player#69]
Error: Could not resolve './session' from src/client/rtsp/client.js

**Comment by chris-waller** [comment]
I'm also having nothing but problems trying to get this to work. Lots of broken references when I try to use anything as-is.

**Comment by gaetancollaud** [comment]
As seen in [commits](https://github.com/Streamedian/html5_rtsp_player/commits/master), 528287bd76b3525e11d01a6c128f2e15bf13340b seems to have broken the build, but the one just before works: 72c04f7cc74e73cccff9f24466048b7b451f205d .

`git checkout 72c04f7cc74e73cccff9f24466048b7b451f205d` and you're good to go (only without the last changes)

**Comment by kreopt** [comment]
Hi! Thanks for feedback. Fixed.

**Comment by gaetancollaud** [comment]
`master` branch works for me now. I think you can close the issue.
