### ISSUE TITLE
How to run ws_rtsp proxy as WSS

### ISSUE THREAD

**Issue by TestTito** [Streamedian/html5_rtsp_player#70]
Hi guys,

The questions is simple, how can we run the proxy as securewebsocket wss://

Thanks

**Comment by kreopt** [comment]
Hi! Proxy itself currently does not support secure sockets. You can use reverse proxy to achieve this goal.

**Comment by TestTito** [comment]
Do you have any hint on how to achieve this?

**Comment by gaetancollaud** [comment]
Just use a proxy like nginx, apache, traefik or other. This proxy will handle ssl connexion and forward in plain websocket to the streamedian proxy.

**Comment by TestTito** [comment]
Do you have any example? I tryed a lot of stuff from google, but can't seem to make this work.

Thanks

**Comment by TestTito** [comment]
if the server is https i add the /myws at the end of the wss server ip("wss://1X.X.X.X/myws")
So every request sent for wss are redirected at ProxyPass /myws and then apache redirects this to
ws://1x.x.x.x:YOUR_WS_PORT

var p = Streamedian.player('test_video', {socket: "wss://1X.X.X.X/myws"});

Add these rules to your default-ssl.conf after the following block:
		BrowserMatch "MSIE [2-6]" \
				nokeepalive ssl-unclean-shutdown \
				downgrade-1.0 force-response-1.0

LINES TO ADD->
RewriteEngine on
ProxyRequests Off
ProxyPreserveHost on
ProxyPass /myws ws://1x.x.x.x:YOUR_WS_PORT
ProxyPassReverse /myws ws://1x.x.x.x.x:YOUR_WS_PORT

if it can help somebody with apache

**Comment by JialuZhang** [comment]
@TestTito 

In your posted configuration,
```
RewriteEngine on
ProxyRequests Off
ProxyPreserveHost on
ProxyPass /myws ws://1x.x.x.x:YOUR_WS_PORT
ProxyPassReverse /myws ws://1x.x.x.x.x:YOUR_WS_PORT

```
the line "RewriteEngine On“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".
That is to say, unless you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then leaving off "RewriteEngine" is a better choice.

More importantly, the default value of “RewriteEngine" is already an "off", so from a security side, deleting “RewriteEngine On” would be ideal.

The related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```

Hope it can help someone with the same issue.
