### ISSUE TITLE
authorization support

### ISSUE THREAD

**Issue by msslava** [Streamedian/html5_rtsp_player#71]
I checked the demo - it works perfectly.
Installed on my server - checked the test stream- it works perfectly.
I wanted to check my camera (with authorization) - it does not work.
Does this module support authorization? If so, how can this be done?
No known method works for me 
(for example, rtsp://admin:admin@ip_address/stream; 
or 
rtsp://ip_address/stream&user=admin&password=admin).
Thanks!

**Comment by kreopt** [comment]
Hi! Authorization is supported, but you should implement queryCredentials method (you can see example in https://github.com/Streamedian/html5_rtsp_player/blob/master/example.js).
