### ISSUE TITLE
RTSP session issue with EvoStream

### ISSUE THREAD

**Issue by gaetancollaud** [Streamedian/html5_rtsp_player#74]
During the `SETUP`part, the player, send two requests directly with no session. Then the server should open two separate session and the player will keep using one session per stream. Not sure if this is correct or not, but it doesn't work with EvoStream. In fact EvoStream wants only one session. If you try to open two sessions, the second request is never answered (even if we do the `SETUP` sequentially). 

In order to make it work we should first `SETUP` one track, wait for the response, and use the session in this first response for all next requests (including the next(s) `SETUP`). This is at least how it is implemented in *VLC* and in *Locomote*. 

I modified a little bit my fork to have only one session and it works great but I'm not sure if this will break the compatibility with other servers.

Do you mind if I create a PR to use only one session across all streams (tracks) ?

**Comment by kreopt** [comment]
Yes, you can PR. I had noticed same behavior on somewhat other stream. But I thought it was fixed

**Comment by gaetancollaud** [comment]
It's really strange because when you look at the [RFC2326](https://www.ietf.org/rfc/rfc2326.txt) chapter 12, it's look like the `Session` field should not appear in `SETUP`. And at chapter 10.4 it is said that the server can refuse to bundle session. But by saying so, it means that we can bundle session... I'm a bit confused

**Comment by gaetancollaud** [comment]
PR is merged, I close this issue
