### ISSUE TITLE
Does UDP works

### ISSUE THREAD

**Issue by TestTito** [Streamedian/html5_rtsp_player#77]
I would like to know if the library can work with UDP:

Transport: RTP/AVP/UDP;unicast;destination=1xx.x.x.x;client_port=5006-5007;server_port=53198-40474;ssrc=2c713c0d;mode=play

This is the error I have on the browser side:

streamedian.min.js:301 [transport:ws] [ctrl]
WSP/1.1 200 OK
seq: 5

RTSP/1.0 200 OK
Server: Regulvar RTSP Server
Cseq: 3
Transport: RTP/AVP/UDP;unicast;destination=1xx.x.x.x;client_port=5006-5007;server_port=53198-40474;ssrc=2c713c0d;mode=play
Session: 1185d20035702ca
Cache-Control: no-cache

streamedian.min.js:301 [client:rtsp] RTSP/1.0 200 OK
Server: Regulvar RTSP Server
Cseq: 3
Transport: RTP/AVP/UDP;unicast;destination=1x.x.x.x;client_port=5006-5007;server_port=53198-40474;ssrc=2c713c0d;mode=play
Session: 1185d20035702ca
Cache-Control: no-cache

streamedian.min.js:14 Uncaught (in promise) No such transition: 8 to 1

Is it cause by the fact that only UDP is supported on that particular device?

Thanks

David

**Comment by kreopt** [comment]
Hi! UDP is currently not supported on server side.

**Comment by TestTito** [comment]
I ended up setuping my device as TCP and it works
