### ISSUE TITLE
how can I use this to play my local h264 player?

### ISSUE THREAD

**Issue by weibinzhu** [Streamedian/html5_rtsp_player#79]
this question might be silly. 

I am trying to use this player to play my local h264 file. And I am thinking to use FileReader to read that file then change it into Uint8Array.

where can I inject the ArrayBuffer? Can I put manually it into the dataQueue and fire data event?

**Comment by kreopt** [comment]
Hi! According to player architecture, to make sure all works ok, you should implement your own transport(method to deliver data to client. FileReader wrapper in your case ) and client(playback controller which allows you to navigate stream and pass chunks to remuxer. in simple case - just parse stream and fire events)
