### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by ravz** [Streamedian/html5_rtsp_player#84]
Hello, how do we handle RTSP authentication using your player ?

**Comment by victorgrenke** [comment]
try   rtsp://<user>:<psw>@192.168.*.*:554/Streaming/Channels/2

**Comment by balajigite16** [comment]
i have tried with my local rtsp camera stream with authentication rtsp://ONVIF1:ONVIF1@192.168.10.10:554/live/00049c14-4bc1-4c86-8b1a-f435739abd1e
it is not playing stream. camera is on and working fine in vlc player
![capture](https://user-images.githubusercontent.com/32266094/39850788-e85a8136-5430-11e8-97a0-828ea5d024c5.PNG)

**Comment by kreopt** [comment]
You can try to override queryCredentials method like it is done in 

https://github.com/Streamedian/html5_rtsp_player/blob/master/example.js

"rtsp://user:password@resource"-style authentication may not work

**Comment by balajigite16** [comment]
my project doesn't support ecmascript 6 does this player available in Javascript,
for authentication should i have to import all the files mentioned in example.js
https://github.com/Streamedian/html5_rtsp_player/blob/master/example.js

**Comment by balajigite16** [comment]
installed WebSocket RTSP Proxy Server: playing fine with demo link, when i add my link with username and password. it doesnt work, attached screen for ref
![withpass](https://user-images.githubusercontent.com/32266094/40036441-23016f64-5825-11e8-88f4-51c27086dc71.PNG)

**Comment by balajigite16** [comment]
installed WebSocket RTSP Proxy Server: playing fine with demo link, when i add my link with username and password. it doesnt work, attached screen for ref
withpass, could you please help me to resolve this.

**Comment by victorgrenke** [comment]
could you say the characteristics of your stream: compression , formats etc?

**Comment by blackjws** [comment]
I have some issue,can't you give me some idea, my rtsp address is :rtsp://admin:qwe123456@183.*.*.*:554/cam/realmonitor?channel=1&subtype=0
,how to change it? thanks

**Comment by leecp-dev** [comment]
> I have some issue,can't you give me some idea, my rtsp address is :rtsp://admin:qwe123456@183._._.*:554/cam/realmonitor?channel=1&subtype=0
> ,how to change it? thanks

hi , Do u resolve this issues ?
