### ISSUE TITLE
failed: Error during WebSocket handshake: Unexpected response code: 502

### ISSUE THREAD

**Issue by balajigite16** [Streamedian/html5_rtsp_player#85]
i have hosted my application on windows machine and added streamedian player with demo rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov link. it is working fine in local machine, but showing error over internet, attached screenshot for your ref.
![capture](https://user-images.githubusercontent.com/32266094/39850238-d9dec8f4-542d-11e8-82f7-f20ffd128b63.PNG)

**Comment by victorgrenke** [comment]
If you installed a ws proxy at your PC ( url is like ws(s)://<your domain name>/ws/ ) and want to watch video from the global network you need install this license on your PC according the instructions. Test license you can generate in your personal cabinet on streamedian.com for your global ip or domain name or both

**Comment by balajigite16** [comment]
what is the license cost?

**Comment by victorgrenke** [comment]
write to    streamedian.player@gmail.com     with this question
