### ISSUE TITLE
Cannot read property 'endpoint' of null

### ISSUE THREAD

**Issue by silentHimalayas** [Streamedian/html5_rtsp_player#88]
when  destroy the  instance, the browser appear  “ Uncaught TypeError: Cannot read property 'endpoint' of null”

Uncaught TypeError: Cannot read property 'endpoint' of null
    at RTSPClientSM.authenticator (streamedian.js:4375)
    at RTSPClientSM.sendRequest (streamedian.js:4328)
    at RTSPStream.sendKeepalive (streamedian.js:3037)
    at keepaliveInterval.setInterval (streamedian.js:3051)

**Comment by dharini08** [comment]
I got the same error "s3.defineService.**endpoint**.hostname ='http://localhost:8080';
                 ^
TypeError: Cannot read property 'endpoint' of undefined
    at Object.<anonymous>" 

while trying to run amazon gamelift in local. 

here is my code snippet:

var ep = new AWS.Endpoint('http://localhost:8080');

var s3 = new AWS.S3({endpoint: ep});

s3.defineService.**endpoint**.hostname ='http://localhost:8080';
