### ISSUE TITLE
Failed to start player: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by AngelWen** [Streamedian/html5_rtsp_player#96]
when running rtsp video,  Failed to start player: Cannot read property 'split' of undefined alert, can you help this issue ?
![image](https://user-images.githubusercontent.com/23227837/46146513-2a42d380-c28d-11e8-8569-39bd64f38aab.png)

**Comment by RuslanSh20** [comment]
Try this URL "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov".
If it is not working, check ports in the router.

**Comment by AngelWen** [comment]
the url was successfully played, is there another way to fix it ?
![image](https://user-images.githubusercontent.com/23227837/46183290-77a95a00-c2fa-11e8-9353-3500e9e739e0.png)

thanks for your help
