### ISSUE TITLE
Error occured: PIPELINE_ERROR_DECODE

### ISSUE THREAD

**Issue by altiux-admin** [Streamedian/html5_rtsp_player#97]
**Thanks for such a wonderful player. it plays well until I get below error on Crome: Version 70.0.3538.67 .**

Error occured: PIPELINE_ERROR_DECODE: Failed to send audio packet for decoding: timestamp=71360000 duration=64000 size=116 side_data_size=0 is_key_frame=1 encrypted=0 discard_padding (us)=(0, 0). Is there any way to fix it or gracefully ignore it.

Sample data.

0: 0
1: 0
2: 0
3: 130
4: 109
5: 111
6: 111
7: 102
8: 0
9: 0
10: 0
11: 16
12: 109
13: 102
14: 104
15: 100
16: 0
17: 0
18: 0
19: 0
20: 0
21: 0
22: 0
23: 80
24: 0
25: 0
26: 0
27: 106
28: 116
29: 114
30: 97
31: 102
32: 0
33: 0
34: 0
35: 16
36: 116
37: 102
38: 104
39: 100
40: 0
41: 0
42: 0
43: 0
44: 0
45: 0
46: 0
47: 1
48: 0
49: 0
50: 0
51: 16
52: 116
53: 102
54: 100
55: 116
56: 0
57: 0
58: 0
59: 0
60: 0
61: 22
62: 137
63: 180
64: 0
65: 0
66: 0
67: 52
68: 116
69: 114
70: 117
71: 110
72: 0
73: 0
74: 15
75: 1
76: 0
77: 0
78: 0
79: 2
80: 0
81: 0
82: 0
83: 138
84: 0
85: 0
86: 21
87: 150
88: 0
89: 0
90: 0
91: 114
92: 2
93: 0
94: 0
95: 0
96: 0
97: 0
98: 0
99: 0
[100 … 129]
100: 0
101: 0
102: 25
103: 129
104: 0
105: 0
106: 0
107: 134
108: 1
109: 1
110: 0
111: 0
112: 0
113: 0
114: 0
115: 0
116: 0
117: 0
118: 0
119: 14
120: 115
121: 100
122: 116
123: 112
124: 0
125: 0
126: 0
127: 0
128: 32
129: 16

**Comment by victorgrenke** [comment]
check the audio format is supported by html5

**Comment by salim-hbk** [comment]
> **Thanks for such a wonderful player. it plays well until I get below error on Crome: Version 70.0.3538.67 .**
> 
> Error occured: PIPELINE_ERROR_DECODE: Failed to send audio packet for decoding: timestamp=71360000 duration=64000 size=116 side_data_size=0 is_key_frame=1 encrypted=0 discard_padding (us)=(0, 0). Is there any way to fix it or gracefully ignore it.
> 
> Sample data.
> 
> 0: 0
> 1: 0
> 2: 0
> 3: 130
> 4: 109
> 5: 111
> 6: 111
> 7: 102
> 8: 0
> 9: 0
> 10: 0
> 11: 16
> 12: 109
> 13: 102
> 14: 104
> 15: 100
> 16: 0
> 17: 0
> 18: 0
> 19: 0
> 20: 0
> 21: 0
> 22: 0
> 23: 80
> 24: 0
> 25: 0
> 26: 0
> 27: 106
> 28: 116
> 29: 114
> 30: 97
> 31: 102
> 32: 0
> 33: 0
> 34: 0
> 35: 16
> 36: 116
> 37: 102
> 38: 104
> 39: 100
> 40: 0
> 41: 0
> 42: 0
> 43: 0
> 44: 0
> 45: 0
> 46: 0
> 47: 1
> 48: 0
> 49: 0
> 50: 0
> 51: 16
> 52: 116
> 53: 102
> 54: 100
> 55: 116
> 56: 0
> 57: 0
> 58: 0
> 59: 0
> 60: 0
> 61: 22
> 62: 137
> 63: 180
> 64: 0
> 65: 0
> 66: 0
> 67: 52
> 68: 116
> 69: 114
> 70: 117
> 71: 110
> 72: 0
> 73: 0
> 74: 15
> 75: 1
> 76: 0
> 77: 0
> 78: 0
> 79: 2
> 80: 0
> 81: 0
> 82: 0
> 83: 138
> 84: 0
> 85: 0
> 86: 21
> 87: 150
> 88: 0
> 89: 0
> 90: 0
> 91: 114
> 92: 2
> 93: 0
> 94: 0
> 95: 0
> 96: 0
> 97: 0
> 98: 0
> 99: 0
> [100 … 129]
> 100: 0
> 101: 0
> 102: 25
> 103: 129
> 104: 0
> 105: 0
> 106: 0
> 107: 134
> 108: 1
> 109: 1
> 110: 0
> 111: 0
> 112: 0
> 113: 0
> 114: 0
> 115: 0
> 116: 0
> 117: 0
> 118: 0
> 119: 14
> 120: 115
> 121: 100
> 122: 116
> 123: 112
> 124: 0
> 125: 0
> 126: 0
> 127: 0
> 128: 32
> 129: 16

As I found it is google only issue All other browsers it is working fine. Thank you Victor for your reply.
