### ISSUE TITLE
Demo no longer works

### ISSUE THREAD

**Issue by MathieuDuponchelle** [Streamedian/html5_rtsp_player#98]
https://streamedian.com/demo/free/  errors out

**Comment by victorgrenke** [comment]
the number of users (watchers) is limited to save traffic

**Comment by MathieuDuponchelle** [comment]
I see, thanks, I assumed as the streamedian website went down a few days ago, the proxy server hadn't been rebooted, if this was actually a traffic limitation issue may I suggest displaying a message in the demo when a new user is rejected?

**Comment by victorgrenke** [comment]
several days ago we had the attack on the server and it was get hangs, it's a pity
